name: CI-CD
on:
  push:
  workflow_dispatch: {}

jobs:
  ci:
    name: Build and publish image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          make test
      - name: Build Docker image
        run: docker build -t callrua/aye-robot:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        run: docker push callrua/aye-robot
