name: CI
on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t aye-robot:latest .
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        run: docker push callrua/aye-robot

